### ISSUE TITLE
OpenSSL. Unexpected eof while reading

### ISSUE THREAD

**Issue by sedlexx** [MIvanchev/static-wine32#10]
I received the following messages during compilation:
```
--2023-10-31 08:31:47--  https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz
Resolving gmplib.org (gmplib.org)... 130.242.124.102
Connecting to gmplib.org (gmplib.org)|130.242.124.102|:443... connected.
OpenSSL: error:0A000126:SSL routines::unexpected eof while reading
Unable to establish SSL connection.
The command '/bin/bash -c build/checkvers.sh && build/download.sh' returned a non-zero code: 1
```
Can you help with this?
P.S. Can you speak russian?

**Comment by MIvanchev** [comment]
> P.S. Can you speak russian?

Привет, плохо =) Ты можешь вручную скачать https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz в директории `dependencies` прежде `docker build`. Также можно заменить ` https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz` с `https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz` в `dependencies/packages.txt`. Я думаю, что сервер `https://gmplib.org` не използует SSL правильно.

**Comment by sedlexx** [comment]
Спасибо! Помогло.
