### ISSUE TITLE
ntdll.so

### ISSUE THREAD

**Issue by sedlexx** [MIvanchev/static-wine32#11]
Прошу прощения за, возможно, глупый вопрос.
Я получил и распаковал wine-build.tar.gz. При попытке использования получил следующее:
```
*@*:~/.local/bin$ ./wine notepad.exe
wine: could not load ntdll.so: /home/*.local/bin/../lib/wine/i386-unix/ntdll.so: cannot open shared object file: No such file or directory
```
Что я делаю не так?
P.S. Статически-слинкованый wine мне требуется для запуска его на ARM с помощью qemu.

**Comment by MIvanchev** [comment]
Проблем сдесь: `/home/*.local/bin/..`. В команды `docker build` ты наверно неправильно задал аргумент `PREFIX`. Если хочешь разпаковать в `/home/my-username/.local`,  задай  `docker build --build-arg PREFIX=/home/my-username/.local`.

>P.S. Статически-слинкованый wine мне требуется для запуска его на ARM с помощью qemu.

Для нещастия static-wine32 только поддерживает x86. Тебе нужно что-то другое, например https://github.com/AndreRH/hangover.
